version: "3.0"
services:
  provider:
    build: ./provider
    hostname: provider
    container_name: dubbo_prov
#    ports:
#      - "2333"
    volumes:
      - /tmp:/tmp
    depends_on:
      - zk
  consumer:
    build: ./consumer
    hostname: consumer
    container_name: dubbo_cons
    ports:
    - "80:8888"
    volumes:
    - /tmp:/tmp
    depends_on:
      - zk
      - provider
  zk:
    image: "zookeeper"
    hostname: zkServer
    container_name: zkServer
#    ports:
#    - "2181"
#    - "2888"
#    - "3888"