server:
  port: 8888
spring:
  application:
    name: dubbo-consumer
  rabbitmq:
    addresses: amqp://rabbit:5672
dubbo:
  registry:
    address: zookeeper://zk:2181 #zk docker-compose中service
  consumer:
    loadbalance: random
#logging:
#  file:
#    name: /tmp/consumer.log

order:
  receive:
    exchange: ordernew
    routingkey: coming