/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tian;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.io.IOException;
import java.util.concurrent.CountDownLatch;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println(new App().getGreeting());
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[]{"classpath:/dubbo-server.xml"});
        context.start();
        System.out.println("provider start");
        new CountDownLatch(1).await();
    }
}
